// track-tutorial-react-js/src/App.js
import React, { useState } from 'react';
import TrackButton from "./components/TrackButton";
import TrackText from "./components/TrackText";

function App() {
  const [text, setText] = useState("");
  const onClick = () => {
    setText("hello track");
  }

  return (
    <div style={{
      textAlign: "center",
    }}>
      <TrackButton onClick={onClick} />
      <TrackText text={text}/>
    </div>
  );
}

export default App;

// track-tutorial-vue-ts/src/App.vue
<template>
  <TrackButton :onClick="onClick" />
  <TrackText :msg='state.text' />
</template>

<script lang="ts">
import { defineComponent, reactive } from 'vue';
import TrackButton from './components/TrackButton.vue';
import TrackText from './components/TrackText.vue';

export default defineComponent({
  name: 'App',
  components: {
    TrackButton,
    TrackText
  },
  setup() {
    const state = reactive({
      text: "",
    });
    const onClick = () => {
      state.text = "hello track";
    };
    return { state, onClick };
  }
});
</script>

<style>
#app {
  text-align: center;
}
</style>
