// track-tutorial-vue-js/src/App.vue
<template>
  <TrackButton :onClick="onClick" />
  <TrackText :msg='text' />
</template>

<script>
import TrackButton from './components/TrackButton.vue'
import TrackText from './components/TrackText.vue'

export default {
  name: 'App',
  components: {
    TrackButton,
    TrackText
  },
  data() {
    return {
      text: ""
    }
  },
  methods: {
    onClick() {
      this.text = "hello track";
    }
  }
}
</script>

<style>
#app {
  text-align: center;
}
</style>

// track-tutorial-react-ts/src/App.tsx
import React, { useState } from 'react';
import { TrackButton } from "./components/TrackButton";
import { TrackText } from "./components/TrackText";

function App() {
  const [text, setText] = useState<string>("");
  const onClick = () => {
    setText("hello track");
  }

  return (
    <div style={{
      textAlign: "center",
    }}>
      <TrackButton onClick={onClick} />
      <TrackText text={text}/>
    </div>
  );
}

export default App;
